### ISSUE TITLE
Add auto-prefixer

### ISSUE THREAD

**Issue by michaelBenin** [ZeeStorm/fix-mah-teeth#1]
https://github.com/ZeeStorm/fix-mah-teeth/blob/master/gulpfile.js#L25
```
import autoprefixer from 'gulp-autoprefixer';


.pipe(autoprefixer(autoprefixerBrowsers))
```

BTW Gulp now supports writing in es2015, gulpfile.babel.js

Coming to cali later this august if you wanna catch up!!!! :)

**Comment by james-hart** [comment]
Hah. I know :) just took the gulp config from an already-built application to quickly throw this together in an hour :D
